@include('admin::layouts.header')
<div class="content-wrapper"><div class="container-xxl flex-grow-1 container-p-y">
  <div class="d-flex justify-content-between align-items-center mb-3"><div><h4 class="mb-1">Vouchers</h4><p class="text-muted mb-0">Single-use, email-bound individual vouchers. Legacy access codes are separate.</p></div><a class="btn btn-primary" href="{{ url('admin/vouchers/create') }}">Create Voucher</a></div>
  @if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
  @if(session('fail'))<div class="alert alert-danger">{{ session('fail') }}</div>@endif
  @if(session('voucher_code'))<div class="alert alert-warning d-flex flex-wrap align-items-center gap-2"><strong>Full redeemable code:</strong><code id="voucher-code" class="fs-5">{{ session('voucher_code') }}</code><button class="btn btn-sm btn-dark" type="button" id="copy-voucher-code">Copy code</button><span class="text-muted small">Give this exact code to {{ session('voucher_code') ? 'the recipient' : '' }}. Do not use the masked table hint.</span></div>@endif
  <div class="card mb-3"><div class="card-body"><form class="row g-2" method="get"><div class="col-md-4"><select class="form-select" name="status"><option value="">All statuses</option>@foreach(['active','claimed','redeemed','disabled','sync_failed','draft'] as $status)<option value="{{ $status }}" @selected(request('status') === $status)>{{ ucfirst(str_replace('_',' ',$status)) }}</option>@endforeach</select></div><div class="col-md-4"><select class="form-select" name="package"><option value="">All packages</option>@foreach($packages as $package)<option value="{{ $package->slug }}" @selected(request('package') === $package->slug)>{{ $package->title }}</option>@endforeach</select></div><div class="col-md-2"><button class="btn btn-outline-primary w-100">Filter</button></div></form></div></div>
  <div class="card"><div class="table-responsive"><table class="table table-hover mb-0"><thead><tr><th>Code reference</th><th>Recipient</th><th>Package</th><th>Purpose</th><th>Value</th><th>Expiry</th><th>Status</th><th>Actions</th></tr></thead><tbody>
  @forelse($vouchers as $voucher)
    <tr><td><span class="text-muted" title="Masked reference only; use Reveal & copy to obtain the real code.">{{ $voucher->code_hint }}</span></td><td>{{ $voucher->recipient_email }}</td><td>{{ $voucher->package_slug }}</td><td>{{ $voucher->purpose === 'permanent_access' ? 'Permanent access' : 'Checkout discount' }}</td><td>@if($voucher->purpose === 'permanent_access')100% permanent@elseif($voucher->discount_type === 'percentage'){{ $voucher->percent_off }}%@else${{ number_format($voucher->amount_off_minor / 100, 2) }}@endif</td><td>{{ $voucher->expires_at?->format('Y-m-d H:i') ?? 'No expiry' }}</td><td><span class="badge bg-label-{{ in_array($voucher->status,['active','redeemed']) ? 'success' : 'warning' }}">{{ str_replace('_',' ', $voucher->status) }}</span></td><td class="d-flex flex-wrap gap-1"><form method="post" action="{{ url('admin/vouchers/'.$voucher->id.'/reveal-code') }}">@csrf<button class="btn btn-sm btn-outline-secondary">Reveal &amp; copy</button></form>@if(in_array($voucher->status,['draft','sync_failed']))<form method="post" action="{{ url('admin/vouchers/'.$voucher->id.'/retry-sync') }}">@csrf<button class="btn btn-sm btn-outline-primary">Retry Stripe</button></form>@endif @if(in_array($voucher->status,['active','claimed','draft','sync_failed']))<form method="post" action="{{ url('admin/vouchers/'.$voucher->id.'/disable') }}">@csrf<button class="btn btn-sm btn-outline-danger" onclick="return confirm('Disable this voucher?')">Disable</button></form>@endif</td></tr>
  @empty<tr><td colspan="8" class="text-center text-muted py-4">No vouchers found.</td></tr>@endforelse
  </tbody></table></div><div class="card-body">{{ $vouchers->links() }}</div></div>
</div></div>
@if(session('voucher_code'))<script>document.getElementById('copy-voucher-code').addEventListener('click',function(){navigator.clipboard.writeText(document.getElementById('voucher-code').textContent.trim()).then(function(){this.textContent='Copied';}.bind(this));});</script>@endif
@include('admin::layouts.footer')
