@extends('public.layout')
@section('title','Bulk assessment enquiry — DecodeMyBrain')
@push('styles')<style>.required-mark{color:#c62828}.enquiry{max-width:700px;margin:0 auto}.enquiry-head{text-align:center;margin-bottom:36px}.enquiry-head .lead{margin:18px auto 0;max-width:620px}.enquiry-intro{margin:0 0 32px;font-size:16px;line-height:1.6}.enquiry-intro p{margin:0 0 20px}.enquiry-intro p:last-child{margin-bottom:0}.submit{width:100%;margin-top:26px}.fine{text-align:center;margin:18px 0 0;color:var(--muted);font-size:14px}</style>@endpush
@section('body')
@include('public.partials.nav')
<main class="page"><div class="enquiry">
@if(session('success'))<div class="alert success">{{ session('success') }}</div>@endif
@if($errors->any())<div class="alert">Please correct the highlighted details and submit again.</div>@endif
<div class="enquiry-head"><span class="eyebrow">Bulk assessment</span><h1 class="heading" style="margin:26px 0 0">Tell us about your group</h1><p class="lead">We reply within one working day to agree numbers and price. Payment is handled offline by invoice or transfer.</p></div>
<div class="enquiry-intro">
  <p><strong>Bring DecodeMyBrain® to your team, organization, school, or community.</strong></p>
  <p>We offer <strong>special corporate and group pricing</strong> based on the number of participants and your requirements.</p>
  <p>Whether you are looking to support <strong>leadership development, team dynamics, career progression, communication, employee wellbeing, or family development,</strong> we can create a package tailored to your group.</p>
  <p><strong>Tell us about your group</strong><br>Share your group size and requirements with us. Our team will respond within <strong>one working day</strong> with a customized package and pricing.</p>
  <p><strong>Payment:</strong> Corporate and group bookings are handled offline via <strong>invoice or bank transfer.</strong></p>
</div>
<p class="help"><span class="required-mark" aria-hidden="true">*</span> All fields are required.</p><form method="post" action="{{ route('organization.enquiry.store') }}">@csrf<div class="form-grid"><div class="field"><label for="organization_name">Organization name <span class="required-mark" aria-hidden="true">*</span></label><input id="organization_name" name="organization_name" value="{{ old('organization_name') }}" placeholder="Acme Secondary School" required></div><div class="field"><label for="group_size">Approximate group size <span class="required-mark" aria-hidden="true">*</span></label><input type="number" min="2" id="group_size" name="group_size" value="{{ old('group_size') }}" placeholder="120" required></div><div class="field"><label for="contact_name">Contact person <span class="required-mark" aria-hidden="true">*</span></label><input id="contact_name" name="contact_name" value="{{ old('contact_name') }}" placeholder="Priya Menon" required></div><div class="field"><label for="contact_phone">Phone <span class="required-mark" aria-hidden="true">*</span></label><input id="contact_phone" name="contact_phone" value="{{ old('contact_phone') }}" placeholder="+971 50 000 0000" required></div><div class="field full"><label for="contact_email">Contact email <span class="required-mark" aria-hidden="true">*</span></label><input type="email" id="contact_email" name="contact_email" value="{{ old('contact_email') }}" placeholder="priya@acme.edu" required></div><div class="field full"><label for="message">Message <span class="required-mark" aria-hidden="true">*</span></label><textarea id="message" name="message" placeholder="We want to assess our Grade 11 cohort before term starts in September." required>{{ old('message') }}</textarea></div></div><button class="button submit" type="submit">Send inquiry</button><p class="fine">You are not buying anything now. This starts a conversation with our team.</p></form></div></main>
@include('public.partials.footer')
@endsection
