@extends('admin::layouts.insights')
@section('title','Business agreement')
@section('eyebrow','Corporate · Agreements')
@section('active','agreements')
@section('actions')<a class="export" href="{{ url('admin/organization-quotes') }}">All agreements</a>@endsection
@section('content')
  @if(session('success'))<div class="alert success">{{ session('success') }}</div>@endif
  @if(session('fail'))<div class="alert fail">{{ session('fail') }}</div>@endif
  @if(session('organization_code'))<div class="alert success"><strong>Enterprise code:</strong> <code id="organization-code">{{ session('organization_code') }}</code> <button class="action-link" type="button" onclick="navigator.clipboard.writeText(document.getElementById('organization-code').textContent).then(()=>this.textContent='Copied')">Copy code</button><div class="secondary">Copy this one-time reveal securely; the table shows a masked reference only.</div></div>@endif
  <div class="split"><section class="panel"><div class="panel-head"><div><h2 class="panel-title">{{ $quote->organization->name }}</h2><p class="panel-sub">{{ $quote->quote_number }} · {{ $quote->organization->contact_email }}</p></div><span class="badge {{ $quote->status === 'paid' ? 'badge-paid' : 'badge-not-started' }}">{{ ucfirst($quote->status) }}</span></div><div style="padding:25px"><div class="form-grid">
    <div class="field"><label>Package</label><input value="{{ $quote->package_slug }}" disabled></div><div class="field"><label>Assessments</label><input value="{{ $quote->seat_count }}" disabled></div>
    <div class="field"><label>Agreed price (total)</label><input value="${{ number_format($quote->total_amount_minor/100,2) }} USD" disabled></div><div class="field"><label>Access</label><input value="{{ ucfirst(str_replace('_',' ',$quote->access_term)) }}" disabled></div>
    <div class="field full"><label>Internal notes</label><textarea disabled>{{ $quote->internal_notes }}</textarea></div>
  </div></div></section><aside><section class="panel payment-card"><h2 class="panel-title">Payment</h2><div class="notice" style="margin-top:18px">Paid offline. Turn on payment received to generate the code and activate seats.</div>@if($quote->status !== 'paid')<form method="post" action="{{ url('admin/organization-quotes/'.$quote->id.'/mark-paid') }}">@csrf<label class="toggle-row"><input class="toggle" type="checkbox" onchange="if(this.checked){if(confirm('Confirm payment has been received?')){this.form.submit()}else{this.checked=false}}"> Payment received</label></form>@else<label class="toggle-row"><input class="toggle" type="checkbox" checked disabled> Payment received</label>@endif</section>
    <section class="panel payment-card" style="margin-top:17px"><h2 class="panel-title">Enterprise code</h2><p class="muted">{{ $quote->shared_code_enabled ? 'Active: '.$quote->shared_code_hint : 'No active enterprise code.' }}</p><div class="table-actions">@if($quote->shared_code_enabled)<form method="post" action="{{ url('admin/organization-quotes/'.$quote->id.'/shared-code/reveal') }}">@csrf<button class="secondary-button">Reveal & copy</button></form>@if($quote->enquiry?->contact_email)<form method="post" action="{{ url('admin/organization-quotes/'.$quote->id.'/shared-code/send-email') }}">@csrf<button class="secondary-button">Send email</button></form>@endif<form method="post" action="{{ url('admin/organization-quotes/'.$quote->id.'/shared-code/disable') }}">@csrf<button class="secondary-button danger-button" onclick="return confirm('Disable this code?')">Disable</button></form>@elseif($quote->status === 'paid')<form method="post" action="{{ url('admin/organization-quotes/'.$quote->id.'/shared-code') }}">@csrf<button class="secondary-button">Generate code</button></form>@endif</div></section></aside></div>
  <section class="panel" style="margin-top:24px"><div class="panel-head"><h2 class="panel-title">Assessment seats</h2><span class="muted">{{ $quote->seats->where('status','claimed')->count() }} registered of {{ $quote->seat_count }}</span></div><div class="table-panel"><table class="data-table"><thead><tr><th>SEAT</th><th>STATUS</th><th>CLAIMED USER</th></tr></thead><tbody>@forelse($quote->seats as $seat)<tr><td>#{{ $seat->id }}</td><td>{{ ucfirst($seat->status) }}</td><td>{{ $seat->claimed_by_wp_user_id ?: '—' }}</td></tr>@empty<tr><td colspan="3" class="empty">Seats will appear when payment is received.</td></tr>@endforelse</tbody></table></div></section>
@endsection
