@include('admin::layouts.header')
<div class="content-wrapper"><div class="container-xxl flex-grow-1 container-p-y">
  <div class="d-flex justify-content-between"><div><h4>{{ $quote->organization->name }}</h4><p class="text-muted mb-0">Agreement: {{ $quote->quote_number }} &middot; {{ $quote->organization->contact_email }}</p></div><a class="btn btn-outline-secondary" href="{{ url('admin/organization-quotes') }}">Back to agreements</a></div>
  @if(session('success')) <div class="alert alert-success mt-3">{{ session('success') }}</div>@endif @if(session('fail')) <div class="alert alert-danger mt-3">{{ session('fail') }}</div>@endif
  @if(session('organization_code'))
    <div class="alert alert-warning mt-3"><strong>Share this enterprise access code:</strong> <code id="organization-code" class="fs-5 ms-2">{{ session('organization_code') }}</code><button type="button" class="btn btn-sm btn-dark ms-3" onclick="navigator.clipboard.writeText(document.getElementById('organization-code').textContent).then(()=>this.textContent='Copied')">Copy code</button><div class="small mt-2">This is the only code members should enter. The agreement reference and masked hint cannot be redeemed.</div></div>
  @endif
  <div class="card mb-3 mt-3"><div class="card-body row g-3"><div class="col-md-3"><strong>Package</strong><br>{{ $quote->package_slug }}</div><div class="col-md-2"><strong>Seats</strong><br>{{ $quote->seat_count }}</div><div class="col-md-3"><strong>Agreed total</strong><br>${{ number_format($quote->total_amount_minor/100,2) }} USD</div><div class="col-md-2"><strong>Payment</strong><br><span class="badge bg-label-{{ $quote->status === 'paid' ? 'success' : 'secondary' }}">{{ ucfirst($quote->status) }}</span></div><div class="col-md-2"><strong>Access</strong><br><span class="badge bg-label-{{ $quote->shared_code_enabled ? 'success' : 'secondary' }}">{{ $quote->shared_code_enabled ? 'Active' : 'Not active' }}</span></div></div></div>
  @if($quote->status !== 'paid')
    <div class="card mb-3"><div class="card-body d-flex flex-wrap justify-content-between align-items-center gap-3"><div><h5 class="mb-1">Payment</h5><p class="text-muted mb-0">Paid offline? Mark payment received to allocate {{ $quote->seat_count }} seats and automatically generate the shared enterprise code.</p></div><form method="post" action="{{ url('admin/organization-quotes/'.$quote->id.'/mark-paid') }}">@csrf<button class="btn btn-success" onclick="return confirm('Confirm that payment has been received? This will activate the organisation access code.')">Mark payment received</button></form></div></div>
  @endif
  <div class="card mb-3"><div class="card-body"><h5>Shared enterprise code</h5><p class="text-muted">One code is shared with the organisation. Each redemption claims one available assessment seat.</p><div class="d-flex flex-wrap align-items-center gap-2"><span class="badge bg-label-{{ $quote->shared_code_enabled ? 'success' : 'secondary' }}">{{ $quote->shared_code_enabled ? 'Active' : 'Not active' }}</span>@if($quote->shared_code_hint)<span class="text-muted" title="Masked reference, not redeemable">{{ $quote->shared_code_hint }}</span>@endif
    @if($quote->shared_code_enabled)<form method="post" action="{{ url('admin/organization-quotes/'.$quote->id.'/shared-code/reveal') }}">@csrf<button class="btn btn-sm btn-primary">Reveal &amp; copy code</button></form><form method="post" action="{{ url('admin/organization-quotes/'.$quote->id.'/shared-code/disable') }}">@csrf<button class="btn btn-sm btn-outline-danger" onclick="return confirm('Disable this shared code?')">Disable code</button></form>@endif
    @if($quote->status === 'paid')<form method="post" action="{{ url('admin/organization-quotes/'.$quote->id.'/shared-code') }}">@csrf<button class="btn btn-sm btn-outline-secondary" onclick="return confirm('Generate a new code? Any previous code will stop working.')">{{ $quote->shared_code_hint ? 'Regenerate code' : 'Generate code' }}</button></form>@endif
  </div></div></div>
  <div class="card"><div class="card-header"><h5 class="mb-0">Assessment seats</h5></div><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Seat</th><th>Status</th><th>Claimed user</th></tr></thead><tbody>@forelse($quote->seats as $seat)<tr><td>#{{ $seat->id }}</td><td>{{ ucfirst($seat->status) }}</td><td>{{ $seat->claimed_by_wp_user_id ?? '—' }}</td></tr>@empty<tr><td colspan="3" class="text-center text-muted py-4">Seats will appear when payment is received.</td></tr>@endforelse</tbody></table></div></div>
</div></div>
@include('admin::layouts.footer')
