@extends('admin::layouts.insights')
@section('title','Dashboard')
@section('active','dashboard')
@section('actions')
  <form method="get"><select class="range range-select" name="range" onchange="this.form.submit()"><option value="7d" @selected($range === '7d')>Last 7 days</option><option value="30d" @selected($range === '30d')>Last 30 days</option><option value="90d" @selected($range === '90d')>Last 90 days</option><option value="all" @selected($range === 'all')>All time</option></select></form>
@endsection
@section('content')
<div class="metric-grid"><div class="metric"><div class="metric-label">Registered users</div><div class="metric-value">{{ number_format($stats['registered']) }}</div><div class="metric-detail">All customer accounts</div></div><div class="metric"><div class="metric-label">Assessments<br>completed</div><div class="metric-value">{{ number_format($stats['completed']) }}</div><div class="metric-detail">Completed attempts</div></div><div class="metric"><div class="metric-label">Revenue (individual)</div><div class="metric-value">${{ number_format($stats['revenue_minor'] / 100, 2) }}</div><div class="metric-detail">Selected period</div></div><div class="metric"><div class="metric-label">Active corporate<br>codes</div><div class="metric-value">{{ number_format($stats['active_codes']) }}</div><div class="metric-detail">Organisation access live</div></div></div>
<div class="cards"><section class="panel"><div class="panel-head"><div><h2 class="panel-title">New corporate inquiries</h2><p class="panel-sub">Needs a first response</p></div><a class="view-link" href="{{ url('admin/organization-enquiries') }}">View all</a></div>@forelse($inquiries as $enquiry)<div class="list-row"><div><div class="row-name">{{ $enquiry->organization_name }}</div><div class="row-detail">{{ number_format($enquiry->group_size) }} people · {{ now()->parse($enquiry->created_at)->timezone(config('app.timezone'))->diffForHumans() }}</div></div><span class="badge {{ $enquiry->status === 'new' ? 'badge-new' : 'badge-talk' }}">{{ $enquiry->status === 'new' ? 'New' : 'In talks' }}</span></div>@empty<div class="empty">No new corporate inquiries.</div>@endforelse</section>
<section class="panel"><div class="panel-head"><div><h2 class="panel-title">Recent payments</h2><p class="panel-sub">Individual purchases</p></div><a class="view-link" href="{{ url('admin/payments') }}">View all</a></div>@forelse($payments->take(3) as $payment)<div class="list-row"><div><div class="row-name">{{ $payment->display_name }}</div><div class="row-detail">{{ $payment->package }}</div></div><div class="amount">${{ number_format($payment->amount_minor / 100, 2) }}</div></div>@empty<div class="empty">No individual payments in this period.</div>@endforelse</section></div>
@endsection
