@extends('admin::layouts.insights')
@section('title','Payments')
@section('active','payments')
@section('eyebrow','Individual')
@section('actions')<div style="display:flex;gap:12px"><form method="get" style="display:inline"><select class="range range-select" name="range" onchange="this.form.submit()"><option value="7d" @selected($range === '7d')>Last 7 days</option><option value="30d" @selected($range === '30d')>This month</option><option value="90d" @selected($range === '90d')>Last 90 days</option><option value="all" @selected($range === 'all')>All time</option></select></form><a class="export" href="{{ url('admin/payments').'?'.http_build_query(['range' => $range, 'export' => 1]) }}">Export</a></div>@endsection
@section('content')
<div class="metric-grid" style="grid-template-columns:repeat(3,1fr);max-width:820px"><div class="metric"><div class="metric-label">Collected this period</div><div class="metric-value">${{ number_format($summary['collected_minor'] / 100, 2) }}</div><div class="metric-detail">{{ $summary['collected_count'] }} payments</div></div><div class="metric"><div class="metric-label">Refunded</div><div class="metric-value">${{ number_format($summary['refunded_minor'] / 100, 2) }}</div><div class="metric-detail" style="color:var(--muted)">{{ $summary['refunded_count'] }} refunds</div></div><div class="metric"><div class="metric-label">Failed</div><div class="metric-value">{{ $summary['failed_count'] }}</div><div class="metric-detail" style="color:var(--muted)">Payment attempts</div></div></div>
<section class="panel table-panel" style="margin-top:27px"><table class="data-table"><thead><tr><th>TRANSACTION</th><th>CUSTOMER</th><th>PLAN</th><th>COUPON</th><th>AMOUNT</th><th>STATUS</th></tr></thead><tbody>@forelse($rows as $payment)<tr><td style="font-family:'DM Mono',monospace">{{ mb_strimwidth($payment->transaction_id, 0, 13, '…') }}</td><td><div class="row-name">{{ $payment->display_name }}</div><div class="secondary">{{ $payment->email ?: '' }}</div></td><td>{{ $payment->package }}</td><td>{{ $payment->coupon }}</td><td class="amount">${{ number_format($payment->amount_minor / 100, 2) }}</td><td><span class="badge {{ $payment->status === 'Paid' ? 'badge-paid' : ($payment->status === 'Refunded' ? 'badge-refunded' : 'badge-failed') }}">{{ $payment->status }}</span></td></tr>@empty<tr><td colspan="6" class="empty">No individual payments in this period.</td></tr>@endforelse</tbody></table></section>
@endsection
