@extends('admin::layouts.insights')
@section('title','Payments')
@section('active','payments')
@section('eyebrow','Individual')
@section('actions')<a class="export" href="{{ url('admin/payments').'?'.http_build_query(array_merge(request()->query(), ['export' => 1])) }}">Export</a>@endsection
@section('content')
<div class="metric-grid" style="grid-template-columns:1fr;max-width:390px"><div class="metric"><div class="metric-label">Receipts till {{ $receiptsTill }}</div><div class="metric-value">${{ number_format($summary['collected_minor'] / 100, 2) }}</div><div class="metric-detail">{{ $summary['collected_count'] }} payments</div></div></div>
<form method="get" class="toolbar" style="margin-top:27px"><input class="search" type="search" name="search" value="{{ $search }}" placeholder="Search customer, email or phone"><div class="filters"><select class="range range-select" name="plan"><option value="">All plans</option>@foreach($plans as $availablePlan)<option value="{{ $availablePlan->slug }}" @selected($plan === $availablePlan->slug)>{{ $availablePlan->title }}</option>@endforeach</select><select class="range range-select" name="range"><option value="7d" @selected($range === '7d')>Last 7 days</option><option value="30d" @selected($range === '30d')>This month</option><option value="90d" @selected($range === '90d')>Last 90 days</option><option value="all" @selected($range === 'all')>All time</option></select><button class="filter" type="submit">Filter</button></div></form>
<section class="panel table-panel"><table class="data-table"><thead><tr><th>SL#</th><th>CUSTOMER</th><th>PLAN</th><th>COUPON</th><th>TRANSACTION ID</th><th>AMOUNT</th><th>STATUS</th><th>PAYMENT DATE &amp; TIME</th></tr></thead><tbody>@forelse($payments as $payment)<tr><td>{{ $payment->sl_no }}</td><td><div class="row-name">{{ $payment->display_name }}</div><div class="secondary">{{ $payment->email ?: '—' }}</div><div class="secondary">{{ $payment->phone ?: '—' }}</div></td><td>{{ $payment->package }}</td><td>{{ $payment->coupon }}</td><td style="font-family:'DM Mono',monospace">{{ mb_strimwidth($payment->transaction_id, 0, 18, '…') }}</td><td class="amount">${{ number_format($payment->amount_minor / 100, 2) }}</td><td><span class="badge {{ $payment->status === 'Paid' ? 'badge-paid' : ($payment->status === 'Refunded' ? 'badge-refunded' : 'badge-failed') }}">{{ $payment->status }}</span></td><td>{{ $payment->status === 'Paid' ? $payment->created_at->format('d M Y, h:i A') : '—' }}</td></tr>@empty<tr><td colspan="8" class="empty">No individual payments match these filters.</td></tr>@endforelse</tbody></table></section>
@if($payments->hasPages())<nav style="display:flex;justify-content:flex-end;gap:8px;margin-top:20px" aria-label="Payment pagination">@if($payments->onFirstPage())<span class="filter" style="opacity:.5">Previous</span>@else<a class="filter" href="{{ $payments->previousPageUrl() }}">Previous</a>@endif<span class="filter" style="cursor:default">Page {{ $payments->currentPage() }} of {{ $payments->lastPage() }}</span>@if($payments->hasMorePages())<a class="filter" href="{{ $payments->nextPageUrl() }}">Next</a>@else<span class="filter" style="opacity:.5">Next</span>@endif</nav>@endif
@endsection
