@extends('admin::layouts.insights')
@section('title','Users')
@section('active','users')
@section('eyebrow','Individual')
@section('actions')<a class="export" href="{{ url('admin/users').'?'.http_build_query(array_filter(['search' => $search, 'filter' => $filter, 'export' => 1])) }}">Export CSV</a>@endsection
@section('content')
<div class="toolbar"><form method="get"><input class="search" type="search" name="search" value="{{ $search }}" placeholder="⌕  Search name or email"><input type="hidden" name="filter" value="{{ $filter }}"></form><div class="filters">@foreach(['all' => 'All', 'completed' => 'Completed', 'progress' => 'In progress', 'corporate' => 'Corporate'] as $key => $label)<a class="filter {{ $filter === $key ? 'active' : '' }}" href="{{ url('admin/users').'?'.http_build_query(array_filter(['search' => $search, 'filter' => $key])) }}">{{ $label }}</a>@endforeach</div></div>
<section class="panel table-panel"><table class="data-table"><thead><tr><th>USER</th><th>JOINED VIA</th><th>ASSESSMENT</th><th>REGISTERED</th><th>STATUS</th></tr></thead><tbody>@forelse($rows as $user)<tr><td><div class="person"><span class="initials">{{ strtoupper(mb_substr($user->display_name ?: 'U', 0, 1).mb_substr(strstr($user->display_name ?: '', ' ') ?: '', 1, 1)) }}</span><div><div class="row-name">{{ $user->display_name ?: 'Unnamed user' }}</div><div class="secondary">{{ $user->email ?: '—' }}</div></div></div></td><td>{{ $user->joined_via }}</td><td><div class="progress"><span style="width:{{ $user->progress }}%"></span></div></td><td>{{ $user->registered_at ? now()->parse($user->registered_at)->timezone(config('app.timezone'))->format('j M Y') : '—' }}</td><td><span class="badge {{ $user->assessment_status === 'Completed' ? 'badge-complete' : ($user->assessment_status === 'In progress' ? 'badge-progress' : 'badge-not-started') }}">{{ $user->assessment_status }}</span></td></tr>@empty<tr><td colspan="5" class="empty">No users match the selected filter.</td></tr>@endforelse</tbody></table></section>
@endsection
